name: Link Checker

on:
  schedule:
    - cron: '0 0 1 * *' # 每月的 UTC 时间 00:00（即每月的第一天）
  workflow_dispatch: # 允许手动触发

jobs:
  link-check:
    runs-on: ubuntu-last

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 可以根据需要修改 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Link Checker
        run: |
          python main.py ./data/webstack.yml ./content/invalidlinks.md  # 修改路径
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 用于访问 GitHub API（如果需要）

      - name: Commit and push changes
        run: |
          git config --local user.name "rcy1314"
          git config --local user.email "1129159201@qq.com"
          git add ./data/webstack.yml ./content/invalidlinks.md  # 修改路径
          git commit -m "Update links after check" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 用于访问 GitHub API
